const eredivisieTeams = [
    //todo fix the image urls apart from feyenoord and ajax
    {
        title: "Ajax",
        description: "AFC Ajax — Amsterdam based football club",
        review: 9,
        loc: { type: "Point", coordinates: [4.941, 52.314] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Logo_AFC_Ajax_%281928-1991%2C_2025-%29.png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "AZ Alkmaar",
        description: "AZ Alkmaar — North Holland football club",
        review: 8,
        loc: { type: "Point", coordinates: [4.754, 52.632] },
        imageUrl: "https://en.wikipedia.org/wiki/AZ_Alkmaar#/media/File:AZ_Alkmaar.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Excelsior",
        description: "SBV Excelsior — Rotterdam based club",
        review: 7,
        loc: { type: "Point", coordinates: [4.494, 51.924] },
        imageUrl: "https://nl.wikipedia.org/wiki/Excelsior_Rotterdam#/media/Bestand:Excelsior_Rotterdam_logo_2021.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "FC Groningen",
        description: "Football Club Groningen — Groningen based club",
        review: 7,
        loc: { type: "Point", coordinates: [6.566, 53.219] },
        imageUrl: "https://nl.wikipedia.org/wiki/FC_Groningen#/media/Bestand:FC_Groningen_logo.png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "FC Twente",
        description: "FC Twente — Enschede based club",
        review: 8,
        loc: { type: "Point", coordinates: [6.875, 52.223] },
        imageUrl: "https://en.wikipedia.org/wiki/FC_Twente#/media/File:FC_Twente.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "FC Utrecht",
        description: "FC Utrecht — Utrecht based football club",
        review: 7,
        loc: { type: "Point", coordinates: [5.121, 52.090] },
        imageUrl: "https://en.wikipedia.org/wiki/FC_Utrecht#/media/File:Logo_FC_Utrecht.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "FC Volendam",
        description: "FC Volendam — Volendam football club",
        review: 7,
        loc: { type: "Point", coordinates: [5.064, 52.499] },
        imageUrl: "https://en.wikipedia.org/wiki/FC_Volendam#/media/File:FC_Volendam_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Feyenoord",
        description: "Feyenoord — Rotterdam football club",
        review: 9,
        loc: { type: "Point", coordinates: [4.479, 51.856] },
        imageUrl: "https://nl.wikipedia.org/wiki/Feyenoord#/media/Bestand:Feyenoord_logo_since_2024.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Fortuna Sittard",
        description: "Fortuna Sittard — Sittard based club",
        review: 7,
        loc: { type: "Point", coordinates: [5.871, 50.999] },
        imageUrl: "https://nl.wikipedia.org/wiki/Fortuna_Sittard#/media/Bestand:Fortuna_Sittard_logo_(PNG).png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Go Ahead Eagles",
        description: "Go Ahead Eagles — Deventer football club",
        review: 8,
        loc: { type: "Point", coordinates: [6.212, 52.257] },
        imageUrl: "https://nl.wikipedia.org/wiki/Go_Ahead_Eagles#/media/Bestand:Go_Ahead_Eagles_logo_2015-heden.png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Heracles Almelo",
        description: "Heracles Almelo — Almelo football club",
        review: 7,
        loc: { type: "Point", coordinates: [6.664, 52.366] },
        imageUrl: "https://en.wikipedia.org/wiki/Heracles_Almelo#/media/File:Heracles_Almelo_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "NAC Breda",
        description: "NAC Breda — Breda based club",
        review: 7,
        loc: { type: "Point", coordinates: [4.768, 51.588] },
        imageUrl: "https://en.wikipedia.org/wiki/NAC_Breda#/media/File:Logo_NAC_Breda.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "NEC Nijmegen",
        description: "NEC — Nijmegen football club",
        review: 7,
        loc: { type: "Point", coordinates: [5.852, 51.812] },
        imageUrl: "https://en.wikipedia.org/wiki/NEC_Nijmegen#/media/File:LogoN.E.C.png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "PEC Zwolle",
        description: "PEC Zwolle — Zwolle based club",
        review: 7,
        loc: { type: "Point", coordinates: [6.093, 52.512] },
        imageUrl: "https://en.wikipedia.org/wiki/PEC_Zwolle#/media/File:PEC_Zwolle_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "PSV Eindhoven",
        description: "PSV Eindhoven — Eindhoven football club",
        review: 9,
        loc: { type: "Point", coordinates: [5.478, 51.441] },
        imageUrl: "https://en.wikipedia.org/wiki/PSV_Eindhoven#/media/File:PSV_Eindhoven.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "SC Heerenveen",
        description: "SC Heerenveen — Heerenveen based club",
        review: 7,
        loc: { type: "Point", coordinates: [5.986, 53.146] },
        imageUrl: "https://en.wikipedia.org/wiki/SC_Heerenveen#/media/File:SC_Heerenveen_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Sparta Rotterdam",
        description: "Sparta Rotterdam — Rotterdam club",
        review: 7,
        loc: { type: "Point", coordinates: [4.464, 51.926] },
        imageUrl: "https://en.wikipedia.org/wiki/Sparta_Rotterdam#/media/File:Sparta_Rotterdam_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Telstar",
        description: "SC Telstar — Velsen based club",
        review: 6,
        loc: { type: "Point", coordinates: [4.637, 52.490] },
        imageUrl: "https://en.wikipedia.org/wiki/SC_Telstar#/media/File:SC_Telstar.png",
        hasBookmark: false,
        date: new Date(),
    },
];

export default eredivisieTeams;
