const eredivisieTeams = [
    {
        title: "Ajax",
        description: "AFC Ajax — Amsterdam based football club",
        review: 9,
        loc: { type: "Point", coordinates: [4.941, 52.314] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Logo_AFC_Ajax_%281928-1991%2C_2025-%29.png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "AZ Alkmaar",
        description: "AZ Alkmaar — North Holland football club",
        review: 8,
        loc: { type: "Point", coordinates: [4.754, 52.632] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e0/AZ_Alkmaar.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Excelsior",
        description: "SBV Excelsior — Rotterdam based club",
        review: 7,
        loc: { type: "Point", coordinates: [4.494, 51.924] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Excelsior_Rotterdam_logo_2021.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "FC Groningen",
        description: "Football Club Groningen — Groningen based club",
        review: 7,
        loc: { type: "Point", coordinates: [6.566, 53.219] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cf/FC_Groningen_logo.png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "FC Twente",
        description: "FC Twente — Enschede based club",
        review: 8,
        loc: { type: "Point", coordinates: [6.875, 52.223] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/e/e3/FC_Twente.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "FC Utrecht",
        description: "FC Utrecht — Utrecht based football club",
        review: 7,
        loc: { type: "Point", coordinates: [5.121, 52.090] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5d/Logo_FC_Utrecht.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "FC Volendam",
        description: "FC Volendam — Volendam football club",
        review: 7,
        loc: { type: "Point", coordinates: [5.064, 52.499] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/0/0e/FC_Volendam_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Feyenoord",
        description: "Feyenoord — Rotterdam football club",
        review: 9,
        loc: { type: "Point", coordinates: [4.479, 51.856] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Feyenoord_logo_since_2024.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Fortuna Sittard",
        description: "Fortuna Sittard — Sittard based club",
        review: 7,
        loc: { type: "Point", coordinates: [5.871, 50.999] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Fortuna_Sittard_logo_%28PNG%29.png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Go Ahead Eagles",
        description: "Go Ahead Eagles — Deventer football club",
        review: 8,
        loc: { type: "Point", coordinates: [6.212, 52.257] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/70/Go_Ahead_Eagles_logo_2015-heden.png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Heracles Almelo",
        description: "Heracles Almelo — Almelo football club",
        review: 7,
        loc: { type: "Point", coordinates: [6.664, 52.366] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/9/9e/Heracles_Almelo_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "NAC Breda",
        description: "NAC Breda — Breda based club",
        review: 7,
        loc: { type: "Point", coordinates: [4.768, 51.588] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c9/Logo_NAC_Breda.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "NEC Nijmegen",
        description: "NEC — Nijmegen football club",
        review: 7,
        loc: { type: "Point", coordinates: [5.852, 51.812] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/ca/LogoN.E.C.png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "PEC Zwolle",
        description: "PEC Zwolle — Zwolle based club",
        review: 7,
        loc: { type: "Point", coordinates: [6.093, 52.512] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/f/f3/PEC_Zwolle_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "PSV Eindhoven",
        description: "PSV Eindhoven — Eindhoven football club",
        review: 9,
        loc: { type: "Point", coordinates: [5.478, 51.441] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/0/05/PSV_Eindhoven.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "SC Heerenveen",
        description: "SC Heerenveen — Heerenveen based club",
        review: 7,
        loc: { type: "Point", coordinates: [5.986, 53.146] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/e/e1/SC_Heerenveen_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Sparta Rotterdam",
        description: "Sparta Rotterdam — Rotterdam club",
        review: 7,
        loc: { type: "Point", coordinates: [4.464, 51.926] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/9/9f/Sparta_Rotterdam_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Telstar",
        description: "SC Telstar — Velsen based club",
        review: 6,
        loc: { type: "Point", coordinates: [4.637, 52.490] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/4/46/SC_Telstar.png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Real Madrid",
        description: "Real Madrid CF — Spanish club from Madrid",
        review: 10,
        loc: { type: "Point", coordinates: [-3.7038, 40.4168] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "FC Barcelona",
        description: "FC Barcelona — Spanish club from Barcelona",
        review: 10,
        loc: { type: "Point", coordinates: [2.1734, 41.3851] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Atletico Madrid",
        description: "Atlético de Madrid — Spanish club from Madrid",
        review: 9,
        loc: { type: "Point", coordinates: [-3.7038, 40.4168] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/f/f9/Atletico_Madrid_Logo_2024.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Sevilla FC",
        description: "Sevilla FC — Spanish club from Sevilla",
        review: 8,
        loc: { type: "Point", coordinates: [-5.9845, 37.3891] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/3/3b/Sevilla_FC_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Valencia CF",
        description: "Valencia CF — Spanish club from Valencia",
        review: 8,
        loc: { type: "Point", coordinates: [-0.3763, 39.4699] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/c/ce/Valenciacf.svg",
        hasBookmark: false,
        date: new Date(),
    },
    // **ENGELAND**
    {
        title: "Manchester United",
        description: "Manchester United FC — English club from Manchester",
        review: 10,
        loc: { type: "Point", coordinates: [-2.2900, 53.4631] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Liverpool FC",
        description: "Liverpool FC — English club from Liverpool",
        review: 10,
        loc: { type: "Point", coordinates: [-2.9916, 53.4084] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Chelsea FC",
        description: "Chelsea FC — English club from London",
        review: 9,
        loc: { type: "Point", coordinates: [-0.1632, 51.4839] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Arsenal FC",
        description: "Arsenal FC — English club from London",
        review: 9,
        loc: { type: "Point", coordinates: [-0.1054, 51.5560] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Manchester City",
        description: "Manchester City FC — English club from Manchester",
        review: 10,
        loc: { type: "Point", coordinates: [-2.2004, 53.4831] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Tottenham Hotspur",
        description: "Tottenham Hotspur FC — English club from London",
        review: 8,
        loc: { type: "Point", coordinates: [-0.0680, 51.6050] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg",
        hasBookmark: false,
        date: new Date(),
    },
    // **DUITSLAND**
    {
        title: "Bayern Munich",
        description: "FC Bayern München — German club from Munich",
        review: 10,
        loc: { type: "Point", coordinates: [11.5755, 48.1374] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8d/FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Borussia Dortmund",
        description: "Borussia Dortmund — German club from Dortmund",
        review: 9,
        loc: { type: "Point", coordinates: [7.4653, 51.5136] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/67/Borussia_Dortmund_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "RB Leipzig",
        description: "RB Leipzig — German club from Leipzig",
        review: 8,
        loc: { type: "Point", coordinates: [12.3731, 51.3397] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/0/04/RB_Leipzig_2014_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Bayer Leverkusen",
        description: "Bayer 04 Leverkusen — German club from Leverkusen",
        review: 8,
        loc: { type: "Point", coordinates: [6.9875, 51.0453] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Eintracht Frankfurt",
        description: "Eintracht Frankfurt — German club from Frankfurt",
        review: 8,
        loc: { type: "Point", coordinates: [8.6821, 50.1109] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/7/7e/Eintracht_Frankfurt_crest.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "VfB Stuttgart",
        description: "VfB Stuttgart — German club from Stuttgart", /* zie web */
        review: 7,
        loc: { type: "Point", coordinates: [9.1829, 48.7758] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/eb/VfB_Stuttgart_1893_Logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    // **ITALIË**
    {
        title: "Juventus",
        description: "Juventus FC — Italian club from Turin",
        review: 10,
        loc: { type: "Point", coordinates: [7.6869, 45.0703] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Juventus_FC_-_logo_black_%28Italy%2C_2020%29.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Inter Milan",
        description: "FC Internazionale Milano — Italian club from Milan",
        review: 9,
        loc: { type: "Point", coordinates: [9.1900, 45.4642] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/05/FC_Internazionale_Milano_2021.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "AC Milan",
        description: "AC Milan — Italian club from Milan",
        review: 9,
        loc: { type: "Point", coordinates: [9.1900, 45.4642] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "AS Roma",
        description: "AS Roma — Italian club from Rome",
        review: 8,
        loc: { type: "Point", coordinates: [12.4964, 41.9028] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/f/f7/AS_Roma_logo_%282017%29.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "SSC Napoli",
        description: "SSC Napoli — Italian club from Naples",
        review: 8,
        loc: { type: "Point", coordinates: [14.2681, 40.8518] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2d/SSC_Neapel.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Lazio",
        description: "SS Lazio — Italian club from Rome",
        review: 8,
        loc: { type: "Point", coordinates: [12.4964, 41.9028] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/c/ce/S.S._Lazio_badge.svg",
        hasBookmark: false,
        date: new Date(),
    },
    // **FRANKRIJK**
    {
        title: "Paris Saint-Germain",
        description: "Paris Saint-Germain — French club from Paris",
        review: 10,
        loc: { type: "Point", coordinates: [2.3522, 48.8566] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Olympique Lyonnais",
        description: "Olympique Lyonnais — French club from Lyon", /* web */
        review: 8,
        loc: { type: "Point", coordinates: [4.8357, 45.7640] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/1/1c/Olympique_Lyonnais_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Olympique de Marseille",
        description: "Olympique de Marseille — French club from Marseille",
        review: 9,
        loc: { type: "Point", coordinates: [5.3698, 43.2965] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d8/Olympique_Marseille_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "LOSC Lille",
        description: "LOSC Lille — French club from Lille",
        review: 8,
        loc: { type: "Point", coordinates: [3.0573, 50.6292] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/3/3f/Lille_OSC_2018_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "AS Monaco",
        description: "AS Monaco — club from Monaco",
        review: 8,
        loc: { type: "Point", coordinates: [7.4246, 43.7384] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/c/cf/LogoASMonacoFC2021.svg",
        hasBookmark: false,
        date: new Date(),
    },
    // **PORTUGAL**
    {
        title: "FC Porto",
        description: "FC Porto — Portuguese club from Porto",
        review: 9,
        loc: { type: "Point", coordinates: [-8.6291, 41.1579] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/f/f1/FC_Porto.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "SL Benfica",
        description: "SL Benfica — Portuguese club from Lisbon",
        review: 9,
        loc: { type: "Point", coordinates: [-9.1393, 38.7223] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5d/Emblema_Benfica_1930_%28Sem_fundo%29.png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Sporting CP",
        description: "Sporting CP — Portuguese club from Lisbon",
        review: 8,
        loc: { type: "Point", coordinates: [-9.1393, 38.7223] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/9/95/Sporting_CP_crest.svg",
        hasBookmark: false,
        date: new Date(),
    },
    // **BELGIË**
    {
        title: "Club Brugge",
        description: "Club Brugge KV — Belgian club from Bruges",
        review: 8,
        loc: { type: "Point", coordinates: [3.2247, 51.2093] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/d/d0/Club_Brugge_KV_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "RSC Anderlecht",
        description: "RSC Anderlecht — Belgian club from Anderlecht/Brussels",
        review: 8,
        loc: { type: "Point", coordinates: [4.3350, 50.8503] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/7/77/R.S.C._Anderlecht.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "KRC Genk",
        description: "KRC Genk — Belgian club from Genk",
        review: 7,
        loc: { type: "Point", coordinates: [5.5058, 50.9645] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/77/Logo_KRC_Genk.png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Standard Liège",
        description: "Standard Liège — Belgian club from Liège",
        review: 7,
        loc: { type: "Point", coordinates: [5.5736, 50.6326] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/7/7e/Standard_Li%C3%A8ge_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Royal Antwerp",
        description: "Royal Antwerp FC — Belgian club from Antwerp",
        review: 7,
        loc: { type: "Point", coordinates: [4.4025, 51.2194] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/0/0b/Royal_Antwerp_Football_Club_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    // **POLEN**
    {
        title: "Legia Warsaw",
        description: "Legia Warsaw — Polish club from Warsaw", /* web */
        review: 7,
        loc: { type: "Point", coordinates: [21.0122, 52.2297] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Legia_Warszawa.png",
        hasBookmark: false,
        date: new Date(),
    },
    // **HONGARIJE**
    {
        title: "Ferencvárosi TC",
        description: "Ferencvárosi TC — Hungarian club from Budapest", /* web */
        review: 7,
        loc: { type: "Point", coordinates: [19.0402, 47.4979] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/37/Ferencvarosi_TC.svg",
        hasBookmark: false,
        date: new Date(),
    },
    // **FINLAND**
    {
        title: "HJK Helsinki",
        description: "HJK Helsinki — Finnish club from Helsinki", /* web */
        review: 6,
        loc: { type: "Point", coordinates: [24.9384, 60.1699] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/0/02/HJK_Helsinki_Logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
];

export default eredivisieTeams;
