const eredivisieTeams = [
    {
        title: "Ajax",
        description: "AFC Ajax — Amsterdam based football club",
        review: 9,
        loc: { type: "Point", coordinates: [4.941, 52.314] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Logo_AFC_Ajax_%281928-1991%2C_2025-%29.png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "AZ Alkmaar",
        description: "AZ Alkmaar — North Holland football club",
        review: 8,
        loc: { type: "Point", coordinates: [4.754, 52.632] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e0/AZ_Alkmaar.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Excelsior",
        description: "SBV Excelsior — Rotterdam based club",
        review: 7,
        loc: { type: "Point", coordinates: [4.494, 51.924] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Excelsior_Rotterdam_logo_2021.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "FC Groningen",
        description: "Football Club Groningen — Groningen based club",
        review: 7,
        loc: { type: "Point", coordinates: [6.566, 53.219] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cf/FC_Groningen_logo.png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "FC Twente",
        description: "FC Twente — Enschede based club",
        review: 8,
        loc: { type: "Point", coordinates: [6.875, 52.223] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/e/e3/FC_Twente.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "FC Utrecht",
        description: "FC Utrecht — Utrecht based football club",
        review: 7,
        loc: { type: "Point", coordinates: [5.121, 52.090] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5d/Logo_FC_Utrecht.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "FC Volendam",
        description: "FC Volendam — Volendam football club",
        review: 7,
        loc: { type: "Point", coordinates: [5.064, 52.499] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/0/0e/FC_Volendam_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Feyenoord",
        description: "Feyenoord — Rotterdam football club",
        review: 9,
        loc: { type: "Point", coordinates: [4.479, 51.856] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Feyenoord_logo_since_2024.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Fortuna Sittard",
        description: "Fortuna Sittard — Sittard based club",
        review: 7,
        loc: { type: "Point", coordinates: [5.871, 50.999] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Fortuna_Sittard_logo_%28PNG%29.png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Go Ahead Eagles",
        description: "Go Ahead Eagles — Deventer football club",
        review: 8,
        loc: { type: "Point", coordinates: [6.212, 52.257] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/70/Go_Ahead_Eagles_logo_2015-heden.png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Heracles Almelo",
        description: "Heracles Almelo — Almelo football club",
        review: 7,
        loc: { type: "Point", coordinates: [6.664, 52.366] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/9/9e/Heracles_Almelo_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "NAC Breda",
        description: "NAC Breda — Breda based club",
        review: 7,
        loc: { type: "Point", coordinates: [4.768, 51.588] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c9/Logo_NAC_Breda.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "NEC Nijmegen",
        description: "NEC — Nijmegen football club",
        review: 7,
        loc: { type: "Point", coordinates: [5.852, 51.812] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/ca/LogoN.E.C.png",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "PEC Zwolle",
        description: "PEC Zwolle — Zwolle based club",
        review: 7,
        loc: { type: "Point", coordinates: [6.093, 52.512] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/f/f3/PEC_Zwolle_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "PSV Eindhoven",
        description: "PSV Eindhoven — Eindhoven football club",
        review: 9,
        loc: { type: "Point", coordinates: [5.478, 51.441] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/0/05/PSV_Eindhoven.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "SC Heerenveen",
        description: "SC Heerenveen — Heerenveen based club",
        review: 7,
        loc: { type: "Point", coordinates: [5.986, 53.146] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/e/e1/SC_Heerenveen_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Sparta Rotterdam",
        description: "Sparta Rotterdam — Rotterdam club",
        review: 7,
        loc: { type: "Point", coordinates: [4.464, 51.926] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/9/9f/Sparta_Rotterdam_logo.svg",
        hasBookmark: false,
        date: new Date(),
    },
    {
        title: "Telstar",
        description: "SC Telstar — Velsen based club",
        review: 6,
        loc: { type: "Point", coordinates: [4.637, 52.490] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/4/46/SC_Telstar.png",
        hasBookmark: false,
        date: new Date(),
    },
];

export default eredivisieTeams;
